live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#686f9a"
# blue = "#00a3cc"
# cyan = "#7a5ccc"
# green = "#5ccc96"
# magenta = "#f2ce00"
# red = "#e33400"
# white = "#f0f1ce"
# yellow = "#b3a1e6"

# [colors.normal]
# black = "#000000"
# blue = "#00a3cc"
# cyan = "#7a5ccc"
# green = "#5ccc96"
# magenta = "#f2ce00"
# red = "#e33400"
# white = "#686f9a"
# yellow = "#b3a1e6"

# [colors.primary]
# background = "#0f111b"
# foreground = "#ecf0c1"


[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c6c684"

[colors.footer_bar]
background = "#e3c78a"
foreground = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.search.matches]
background = "#f09479"
foreground = "#080808"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[colors.vi_mode_cursor]
cursor = "#e3c78a"
text = "#080808"

[cursor]
thickness = 0.2
unfocused_hollow = true


[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

# [keyboard]
# bindings = [
#   { key = "Escape", mods = "Control", action = "ToggleViMode" },
#   { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
#   { key = "C", mods = "Command", action = "Copy" },
#   { key = "V", mods = "Command", action = "Paste" },
#   { key = "N", mods = "Command", action = "SpawnNewInstance" },
#   { key = "Up", mods = "Command", action = "ScrollPageUp" },
#   { key = "Down", mods = "Command", action = "ScrollPageDown" },
#   { key = "Left", mods = "Command", action = "ScrollToTop" }
#   { key = "Right", mods = "Command", action = "ScrollToBottom" },
#   { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
#   { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
#   { key = "Q", mods = "Command", action = "ReceiveChar" },
#   { key = "W", mods = "Command", action = "ReceiveChar" },
#   { key = "C", mods = "Control", action = "Copy" },
#   { key = "I", mods = "Control", chars = "\u001B[105;5u" },
#   { key = "K", mods = "Control", chars = "\u0003" },
#   { key = "Q", mods = "Control", chars = "\u0011" },
# ]

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 0
y = 0
